const CORRECT_WORD = 1;
const FAKE_WORD = 0;
const PENALTY = -1;
const NUM_WORDS = 10;

const WORD_POOL = [
  // Real words
  { word: "ephemeral",   isReal: true,  definition: "Lasting for a very short time." },
  { word: "laconic",     isReal: true,  definition: "Using very few words." },
  { word: "mellifluous", isReal: true,  definition: "Pleasingly smooth and musical to hear." },
  { word: "sycophant",   isReal: true,  definition: "A person who flatters powerful people for personal gain." },
  { word: "querulous",   isReal: true,  definition: "Complaining in a petulant or whining manner." },
  { word: "pellucid",    isReal: true,  definition: "Translucently clear; easily understood." },
  { word: "loquacious",  isReal: true,  definition: "Tending to talk a great deal." },
  { word: "tenuous",     isReal: true,  definition: "Very weak or slight; insubstantial." },
  { word: "arduous",     isReal: true,  definition: "Involving or requiring strenuous effort." },
  { word: "verbose",     isReal: true,  definition: "Using more words than needed." },
  { word: "pensive",     isReal: true,  definition: "Engaged in deep or serious thought." },
  { word: "taciturn",    isReal: true,  definition: "Reserved or uncommunicative in speech." },
  { word: "gregarious",  isReal: true,  definition: "Fond of company; sociable." },
  { word: "insipid",     isReal: true,  definition: "Lacking flavor, vigor, or interest." },
  { word: "lucid",       isReal: true,  definition: "Clearly expressed; easy to understand." },
  { word: "nocturnal",   isReal: true,  definition: "Done or active at night." },
  { word: "opulent",     isReal: true,  definition: "Ostentatiously rich and luxurious." },
  { word: "pristine",    isReal: true,  definition: "In its original condition; unspoiled." },
  { word: "raucous",     isReal: true,  definition: "Disturbingly harsh and loud." },
  { word: "serene",      isReal: true,  definition: "Calm, peaceful, and untroubled." },
  { word: "tangible",    isReal: true,  definition: "Perceptible by touch; clear and definite." },
  { word: "ubiquitous",  isReal: true,  definition: "Present or found everywhere." },
  { word: "vapid",       isReal: true,  definition: "Offering nothing stimulating or challenging." },
  { word: "wistful",     isReal: true,  definition: "Having a feeling of vague or regretful longing." },
  { word: "candid",      isReal: true,  definition: "Truthful and straightforward; frank." },

  // Made-up words (phonotactically plausible English)
  { word: "bloric",   isReal: false },
  { word: "frandel",  isReal: false },
  { word: "spovit",   isReal: false },
  { word: "trelmic",  isReal: false },
  { word: "glumset",  isReal: false },
  { word: "prantic",  isReal: false },
  { word: "voskel",   isReal: false },
  { word: "dreflun",  isReal: false },
  { word: "snorbel",  isReal: false },
  { word: "klumpit",  isReal: false },
  { word: "frendal",  isReal: false },
  { word: "blostik",  isReal: false },
  { word: "grumvel",  isReal: false },
  { word: "trandel",  isReal: false },
  { word: "plombit",  isReal: false },
  { word: "slorfin",  isReal: false },
  { word: "grendal",  isReal: false },
  { word: "frumkin",  isReal: false },
  { word: "splontic", isReal: false },
  { word: "blarvit",  isReal: false },
  { word: "trondel",  isReal: false },
  { word: "glumbit",  isReal: false },
  { word: "prolvit",  isReal: false },
  { word: "snelbik",  isReal: false },
  { word: "klondel",  isReal: false },
];
